#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libmwaw
Version  : 0.3.14
Release  : 1
URL      : https://dev-www.libreoffice.org/src/libmwaw-0.3.14.tar.xz
Source0  : https://dev-www.libreoffice.org/src/libmwaw-0.3.14.tar.xz
Summary  : Library for reading and converting ClarisWorks, MacWrite, WriteNow word processor documents
Group    : Development/Tools
License  : LGPL-2.1
Requires: libmwaw-bin
Requires: libmwaw-lib
Requires: libmwaw-license
BuildRequires : doxygen
BuildRequires : pkgconfig(librevenge-0.0)
BuildRequires : pkgconfig(librevenge-generators-0.0)
BuildRequires : pkgconfig(zlib)

%description
Library that handles ClarisWorks, MacWrite, WriteNow documents.

%package bin
Summary: bin components for the libmwaw package.
Group: Binaries
Requires: libmwaw-license

%description bin
bin components for the libmwaw package.


%package dev
Summary: dev components for the libmwaw package.
Group: Development
Requires: libmwaw-lib
Requires: libmwaw-bin
Provides: libmwaw-devel

%description dev
dev components for the libmwaw package.


%package doc
Summary: doc components for the libmwaw package.
Group: Documentation

%description doc
doc components for the libmwaw package.


%package lib
Summary: lib components for the libmwaw package.
Group: Libraries
Requires: libmwaw-license

%description lib
lib components for the libmwaw package.


%package license
Summary: license components for the libmwaw package.
Group: Default

%description license
license components for the libmwaw package.


%prep
%setup -q -n libmwaw-0.3.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534632651
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534632651
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libmwaw
cp COPYING.LGPL %{buildroot}/usr/share/doc/libmwaw/COPYING.LGPL
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mwaw2csv
/usr/bin/mwaw2html
/usr/bin/mwaw2raw
/usr/bin/mwaw2svg
/usr/bin/mwaw2text
/usr/bin/mwawFile
/usr/bin/mwawZip

%files dev
%defattr(-,root,root,-)
/usr/include/libmwaw-0.3/libmwaw/MWAWDocument.hxx
/usr/include/libmwaw-0.3/libmwaw/libmwaw.hxx
/usr/lib64/libmwaw-0.3.so
/usr/lib64/pkgconfig/libmwaw-0.3.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libmwaw/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmwaw-0.3.so.3
/usr/lib64/libmwaw-0.3.so.3.0.14

%files license
%defattr(-,root,root,-)
/usr/share/doc/libmwaw/COPYING.LGPL
